name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.1)'
        required: true
        default: 'v1.0.1'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js and npm
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Publish to GitHub
      run: npm run publish
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Check generated files
      run: |
        echo "Checking dist directory contents:"
        Get-ChildItem -Path "./dist" -Recurse | Format-Table -AutoSize
        if (Test-Path "./dist/latest.yml") {
          echo "latest.yml found:"
          Get-Content "./dist/latest.yml"
        } else {
          echo "WARNING: latest.yml not found in dist directory"
        }
